default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: market_place_api_development

test:
  <<: *default
  database: market_place_api_test

production:
  <<: *default
  database: market_place_api_production
  username: market_place_api
  password: <%= ENV['MARKET_PLACE_API_DATABASE_PASSWORD'] %>
